import styles from "./globals.module.scss";
import Providers from "@/providers";
// import { MyProvider } from "@/providers/Context";
// import store from "@/store";
// import { Provider as ReduxProvider } from "react-redux";
// import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.component}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
