// import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/sections/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            border: "1px solid red",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
